dataset_configs:
    bg_coverage_thresh: 0.03
    bg_iou_thresh: 0.01
    bg_ratio: 1
    dis_threshold: 0
    ending_ratio: 0.5
    fg_iou_thresh: 0.9
    fg_ratio: 1
    gt_annotations: data/wetlab/annotations
    incomplete_iou_thresh: 0.3
    incomplete_overlap_thresh: 0.7
    incomplete_ratio: 6
    iou_threshold: 0.3
    prop_per_video: 8
    starting_ratio: 0.5
    test_dict_path: data/wetlab/dict_files
    test_ft_path: data/wetlab/tf_files
    test_prop_file: data/wetlab/prop_files
    testing_epoch_multiplier: 1
    train_dict_path: data/wetlab/dict_files
    train_ft_path: data/wetlab/tf_files
    train_prop_file: data/wetlab/prop_files
    training_epoch_multiplier: 30
    val_dict_path: data/wetlab/dict_files
evaluation:
    nms_threshold: 0.3
    top_k: 200000
graph_configs:
    adj_num: 21
    child_num: 4
    dis_num: 2
    iou_num: 8
model_configs:
    act_feat_dim: 0
    attention_act_feat_dim: 0
    attention_comp_feat_dim: 0
    comp_feat_dim: 0
    dropout: 0.8
    gcn_dropout: 0.7
    lstm_act_feat_dim: 0
    lstm_comp_feat_dim: 0
    num_class: 8
    raw_act_feat_dim: 3
    raw_comp_feat_dim: 9
